/**
 * Comprehensive roast library for AI Roast Mode
 * Organized by intensity level: mild, spicy, nuclear
 */

export const ROAST_LIBRARY = {
  mild: {
    selfie: [
      "This selfie has main character energy... if the movie was a documentary about mediocrity.",
      "You look like you practiced this pose in the mirror for 20 minutes. It shows.",
      "This is the face of someone who says 'living my best life' unironically.",
      "I see you went with the 'I woke up like this' look. Maybe try waking up differently.",
      "Your selfie game is strong. Your everything else game needs work.",
      "This photo screams 'I peaked in high school.'",
      "You're giving LinkedIn profile pic energy on Instagram.",
      "This is what happens when participation trophies grow up and take selfies.",
      "You look like you ask to speak to the manager... of life.",
      "This selfie has the same energy as a motivational poster in a dentist's office.",
      "You're the human equivalent of room temperature water.",
      "This photo has less personality than a stock image.",
      "You look like you clap when the plane lands.",
      "This is giving 'I bring a guitar to parties but only know Wonderwall' vibes.",
      "You look like you still use Internet Explorer by choice.",
      "This selfie has the charisma of a DMV waiting room.",
      "You're giving off strong 'replies all to company emails' energy.",
      "This photo makes plain toast look spicy.",
      "You look like you get excited about tax season.",
      "This is the face of someone who thinks mayonnaise is too spicy.",
      "Your selfie game is as basic as your coffee order.",
      "You look like you read the terms and conditions.",
      "This photo has the excitement level of watching paint dry.",
      "You're the human version of the 'This is fine' meme.",
      "This selfie energy could put an insomniac to sleep.",
      "You look like you alphabetize your spice rack for fun.",
      "This is what 'playing it safe' looks like in photo form.",
      "Your vibe is giving substitute teacher who's trying too hard.",
      "This selfie has the same impact as a whisper in a hurricane.",
      "You look like you still ask for directions instead of using GPS.",
      "This selfie screams 'I correct people's grammar on social media.'",
      "You're giving 'I still use a checkbook at the grocery store' energy.",
      "This photo has the charm of a parking ticket on your windshield.",
      "You look like you get excited about office supply shopping.",
      "This is the face of someone who color-codes their calendar.",
      "Your selfie game is weaker than decaf coffee.",
      "You look like you say 'see you next year' on December 31st.",
      "This photo has 'I enjoy small talk about the weather' written all over it."
    ],
    group: [
      "This looks like the cast of a sitcom that got cancelled after one episode.",
      "Y'all have the chemistry of oil and water.",
      "This is what 'we're totally not forcing this friendship' looks like.",
      "Someone definitely suggested this photo and everyone else just went along with it.",
      "The energy here is giving 'mandatory corporate team building.'",
      "This group has the cohesion of a broken jigsaw puzzle.",
      "Y'all look like you met five minutes ago at a bus stop.",
      "This is the 'we only hang out because our moms are friends' squad.",
      "The vibe check failed harder than my WiFi connection.",
      "This group photo has less coordination than a kindergarten play.",
      "Y'all look like the B-team of the B-team.",
      "This is what happens when the group chat meets in real life.",
      "The chemistry here is weaker than homeopathic medicine.",
      "This looks like a random sampling of people from a DMV line.",
      "Y'all have the collective charisma of a wet napkin.",
      "This group dynamic is shakier than my phone's autocorrect.",
      "You look like extras who wandered onto the wrong movie set.",
      "This is the 'we're only here for the free food' crew.",
      "The energy is giving 'last picked in gym class' reunion.",
      "This group photo has less style than a 2003 flip phone.",
      "Y'all look like you're being held together by social obligation.",
      "This is what 'diversity hire' looks like in friend groups.",
      "The vibe here is as forced as a laugh at your boss's joke.",
      "This group has the excitement of a Monday morning meeting.",
      "Y'all look like the people who show up early to parties.",
      "This photo has 'we peaked at different times' energy.",
      "The chemistry here couldn't light a birthday candle.",
      "This is the 'our parents made us take this photo' squad.",
      "Y'all have the group dynamic of strangers in an elevator.",
      "This looks like a support group for people with no rhythm.",
      "This is the 'we only text in the group chat' crew.",
      "Y'all look like you share one Netflix password and nothing else.",
      "This group has the energy of a carpool that nobody wants to be in.",
      "You're the 'let's never do this again' squad, captured mid-regret.",
      "This photo screams 'we're only friends on social media.'",
      "Y'all have the chemistry of a broken science experiment.",
      "This is what 'tolerating each other for the gram' looks like."
    ],
    general: [
      "This photo has less depth than a kiddie pool.",
      "I've seen more excitement in a retirement home bingo game.",
      "This image has the visual appeal of beige wallpaper.",
      "Your photo game is weaker than gas station coffee.",
      "This has the artistic merit of a parking violation.",
      "I've seen more life in a Windows screensaver.",
      "This photo is the visual equivalent of elevator music.",
      "Your aesthetic is giving 'default settings.'",
      "This has less flavor than unseasoned chicken breast.",
      "The composition here is as balanced as a one-legged flamingo.",
      "This photo has the impact of a foam sword.",
      "I've seen more creativity in a tax form.",
      "This image is as memorable as what you had for lunch three weeks ago.",
      "Your photo skills peaked at 'point and shoot.'",
      "This has the visual interest of watching grass grow.",
      "The energy here is lower than my phone battery.",
      "This photo is the equivalent of a participation award.",
      "I've seen more effort in a microwave dinner.",
      "This has less style than Crocs with socks.",
      "Your photo game is as weak as airplane WiFi.",
      "This image has the charm of a pop-up ad.",
      "The creativity level here is below sea level.",
      "This photo is as original as a remake of a remake.",
      "I've seen more passion in a DMV employee.",
      "This has the wow factor of finding a penny.",
      "Your aesthetic is 'clearance rack at Target.'",
      "This photo has less personality than Siri.",
      "The effort here is minimal and it shows.",
      "This is what 'phoning it in' looks like in photo form.",
      "I've seen more inspiration in a blank canvas.",
      "This photo is as forgettable as last Tuesday's lunch.",
      "Your aesthetic is 'waiting room magazine from 2003.'",
      "This has the creative spark of a wet match.",
      "I've seen more style in a government form.",
      "This image has the excitement of watching ice melt.",
      "Your photo game is as weak as hotel lobby art.",
      "This has less impact than a feather falling on cotton."
    ]
  },

  spicy: {
    selfie: [
      "This selfie is proof that confidence and competence are two very different things.",
      "You look like you peaked at your birth and it's been downhill since.",
      "This is the face that launched a thousand swipe lefts.",
      "Your selfie game is like your life choices - questionable at best.",
      "You're serving 'I'm not like other girls/guys' energy, and you're right - you're worse.",
      "This photo has strong 'my mom says I'm handsome' energy.",
      "You look like the human embodiment of a participation trophy.",
      "This is what delusion looks like when it takes a selfie.",
      "Your face is giving 'genetic lottery participant, not winner.'",
      "This selfie screams 'I have a podcast no one listens to.'",
      "You look like you're one bad day away from starting a cult.",
      "This is the face of someone who thinks they're the exception to the rule. You're not.",
      "Your selfie game is as weak as your jawline.",
      "You look like you practice your signature for when you're never famous.",
      "This photo has 'peaked in middle school' written all over it.",
      "You're the reason Instagram added the 'restrict' feature.",
      "This selfie is a cry for help that no one wants to answer.",
      "You look like you give unsolicited life advice at parties.",
      "This is what 'trying too hard' looks like in its natural habitat.",
      "Your face has 'I'm not mad, I'm disappointed' parent energy.",
      "This selfie is proof that not everyone should have a camera.",
      "You look like you argue with teenagers on TikTok.",
      "This photo has the same energy as a midlife crisis.",
      "You're giving 'I demand to speak to the manager' vibes, but for existence.",
      "This selfie makes me understand why some people believe in natural selection.",
      "You look like you quote yourself in your own Instagram captions.",
      "This is the face of someone who thinks they're deep but they're just a puddle.",
      "Your selfie game is as tragic as your dating history probably is.",
      "You look like you send motivational quotes to your ex at 3 AM.",
      "This photo proves that angles can only do so much.",
      "You're the human equivalent of a browser with 47 tabs open - trying too hard and achieving nothing.",
      "This selfie has 'I argue with strangers on the internet' energy.",
      "You look like you unironically use the phrase 'rise and grind.'",
      "This is the face that makes Tinder consider adding a super-dislike button.",
      "Your energy is giving 'pyramid scheme survivor turned life coach.'",
      "This photo makes me understand why some people choose to be single.",
      "You look like you give Ted Talks in your shower.",
      "This selfie is proof that self-love can go too far."
    ],
    group: [
      "This looks like the 'before' photo in a glow-up challenge that never happened.",
      "Y'all have the collective appeal of a tax audit.",
      "This is what happens when the friend group has no quality control.",
      "Someone in this photo definitely thinks they're the hot one. They're wrong.",
      "This group has more red flags than a communist parade.",
      "Y'all look like you share one brain cell and it's not your turn with it.",
      "This is the 'we peaked at different points and they were all low' crew.",
      "The combined IQ in this photo is still in the double digits.",
      "This group makes the cast of Jersey Shore look classy.",
      "Y'all have the chemistry of bleach and ammonia - toxic and should be kept apart.",
      "This looks like a convention for people who can't take a hint.",
      "Someone's definitely the designated ugly friend here, but plot twist - it's all of you.",
      "This group photo is a masterclass in lowering the bar.",
      "Y'all look like you met in the comment section of a controversial post.",
      "This is what 'quantity over quality' looks like in friendship form.",
      "The energy here is more toxic than a nuclear waste site.",
      "This group has more issues than a magazine subscription.",
      "Y'all look like the people everyone avoids at reunions.",
      "This is the 'we share one personality and it's not good' squad.",
      "The vibe here is as dead as your group chat probably is.",
      "This photo looks like a police lineup for crimes against fashion.",
      "Y'all have the group dynamic of a dysfunctional reality show.",
      "Someone paid for everyone's friendship here and it shows.",
      "This is what happens when desperation forms a group.",
      "The chemistry here couldn't pass a high school science class.",
      "Y'all look like you're one argument away from never speaking again.",
      "This group photo is proof that some people will befriend anyone.",
      "The collective charm here couldn't seduce a desperate cat.",
      "This is the 'we trauma bonded and now we're stuck' crew.",
      "Y'all make a strong argument for social distancing.",
      "This looks like the reunion of everyone who peaked in different decades - all of them bad.",
      "Y'all have the combined charisma of a DMV waiting room at 4:45 PM.",
      "This is what happens when desperation has a group discount.",
      "Someone definitely made this friend group as a tax write-off.",
      "Y'all look like you met at a 'How to Lose Friends and Alienate People' seminar.",
      "This photo has 'last resort friend group' written all over it.",
      "The vibe here is more forced than a landlord's smile on rent day."
    ],
    general: [
      "This photo is visual assault and battery.",
      "I've seen roadkill with better composition.",
      "This image makes me question the point of human evolution.",
      "Your photo skills are a crime against photography.",
      "This has less artistic value than a ransom note.",
      "I've seen more talent in a kindergarten finger painting.",
      "This photo is what regret looks like in JPEG format.",
      "Your aesthetic is 'dumpster fire, but make it boring.'",
      "This image has the appeal of a colonoscopy.",
      "The only thing worse than this photo is having to look at it twice.",
      "This has less class than a school on summer break.",
      "Your photo game is weaker than my will to live after seeing this.",
      "This image is proof that not everyone deserves a camera.",
      "I've seen more creativity in plagiarism.",
      "This photo has the charm of a restraining order.",
      "Your skills peaked at Microsoft Paint and declined from there.",
      "This has less substance than a politician's promise.",
      "The quality here is lower than rock bottom.",
      "This photo is what failure looks like in 4K.",
      "I've seen more effort from people giving up.",
      "This image has the appeal of wet socks.",
      "Your aesthetic is 'randomize all settings and hope.'",
      "This photo makes me understand why some animals eat their young.",
      "The bar was on the floor and you brought a shovel.",
      "This has less hope than a dating app bio that mentions crypto.",
      "Your photo game is a cautionary tale.",
      "This image is what disappointment looks like to parents.",
      "I've seen more potential in a flat tire.",
      "This photo is the visual equivalent of stepping on Lego.",
      "You've managed to make pixels look embarrassed.",
      "This image has the artistic value of a ransacked dumpster.",
      "Your photo is what happens when mediocrity tries to be edgy.",
      "This has less appeal than a root canal appointment.",
      "I've seen more creativity in corporate compliance training.",
      "This photo is the visual equivalent of food poisoning.",
      "Your aesthetic is 'desperation meets delusion.'",
      "This image makes elevator music seem thrilling."
    ]
  },

  nuclear: {
    selfie: [
      "This selfie is exhibit A in the case against human reproduction.",
      "You look like natural selection's biggest oversight.",
      "This is the face that makes paper bags fashionable again.",
      "Your selfie is proof that God has a sense of humor and it's cruel.",
      "You're the reason they put warning labels on gene pools.",
      "This photo makes me pro-choice retroactively.",
      "You look like you were assembled from the clearance bin at Build-A-Human.",
      "This selfie is a compelling argument for bringing back natural predators.",
      "Your face is what happens when genetics gives up halfway through.",
      "This is why some cultures believed cameras steal souls - yours was already gone.",
      "You look like evolution's rough draft that got submitted by accident.",
      "This selfie could be used as birth control - no one wants to risk this outcome.",
      "Your face has 'parents are siblings' energy.",
      "This photo proves that not all life is precious.",
      "You look like you lost a fight with every branch on the ugly tree.",
      "This selfie is why aliens don't visit Earth.",
      "Your face is a monument to wasted potential and poor decisions.",
      "This is what happens when the gene pool needs chlorine.",
      "You look like the 'before' photo that never got an 'after.'",
      "This selfie is proof that mirrors lie or you're delusional.",
      "Your face makes blind people grateful.",
      "This photo has 'disappointment' written in your parents' tears.",
      "You look like you were designed by committee and they all hated each other.",
      "This selfie is what rock bottom looks like when it takes a photo.",
      "Your face is an argument against intelligent design.",
      "This is why some animals abandon their young.",
      "You look like karma's revenge on your parents.",
      "This selfie could end bloodlines.",
      "Your face is what happens when God plays dice and loses.",
      "This photo is proof that life isn't fair - to anyone who has to see it.",
      "You're living proof that contraception should be retroactive.",
      "This selfie is what happens when chromosomes have a train wreck.",
      "Your face is the strongest argument for mandatory masks returning permanently.",
      "You look like natural selection's participation trophy.",
      "This is the face that makes blind dates fake their own death.",
      "Your genetics are a cautionary tale about the dangers of inbreeding.",
      "This selfie could be used as a cure for sex addiction.",
      "You're the reason aliens probe humans - they can't believe we're the same species.",
      "This photo makes me understand why some cultures ban cameras.",
      "Your face is what happens when God hits randomize and walks away."
    ],
    group: [
      "This looks like a support group for people who failed at life.",
      "Y'all have the collective worth of expired coupons.",
      "This is what happens when the bottom of the barrel forms a friend group.",
      "Combined, you still couldn't make one decent person.",
      "This group is proof that misery doesn't always love company - sometimes it tolerates it.",
      "Y'all look like the 'where are they now' segment of a documentary about failure.",
      "This is natural selection's waiting room.",
      "The gene pool needed chlorine and y'all jumped in anyway.",
      "This group has more chromosomes than brain cells.",
      "Y'all make a compelling case for mandatory sterilization.",
      "This looks like a gathering of everyone's worst Tinder date.",
      "Combined IQ: room temperature. In Celsius. In winter.",
      "This is what happens when participation trophies become sentient.",
      "Y'all look like the control group in an experiment about disappointment.",
      "This group photo is a masterclass in collective failure.",
      "Someone's parents are definitely related, possibly all of yours.",
      "This is the 'we share custody of the brain cell' squad.",
      "Y'all have less combined value than NFTs after the crash.",
      "This looks like the reunion of a pyramid scheme's victims.",
      "The only thing y'all have in common is poor judgment.",
      "This group is why some species eat their young.",
      "Y'all make the Donner Party look like good company.",
      "This is what happens when the shallow end of the gene pool has a pool party.",
      "Combined attractiveness: negative integers.",
      "This group is a walking advertisement for contraception.",
      "Y'all look like extras from a PSA about what not to become.",
      "This is the 'our parents are definitely disappointed' club.",
      "The collective potential here couldn't power a calculator.",
      "Y'all are proof that sometimes quantity is much worse than quality.",
      "This group makes solitary confinement look appealing.",
      "This looks like a class action lawsuit against genetics.",
      "Y'all are the human equivalent of a grease fire - ugly, dangerous, and best avoided.",
      "This group photo is why some countries have population control.",
      "Combined, y'all have the appeal of a communicable disease.",
      "This is what happens when the reject pile becomes self-aware.",
      "Y'all look like the control group for a study on failure.",
      "This photo is a compelling argument for selective breeding.",
      "The collective IQ here couldn't solve a children's puzzle.",
      "Y'all make me understand why thanos had a point."
    ],
    general: [
      "This photo is a hate crime against eyeballs.",
      "I've seen more value in medical waste.",
      "This image is what failure looks like if it was radioactive.",
      "Your photo makes me understand why some people choose blindness.",
      "This has less redemptive value than a war crime.",
      "I've seen more hope in a terminal diagnosis.",
      "This photo is the visual equivalent of a school shooting - tragic and preventable.",
      "Your work here makes me sympathize with book burners.",
      "This image is proof that not all art is valid.",
      "The only thing worse than this photo is the person who took it.",
      "This has less worth than cryptocurrency in a power outage.",
      "Your photo is why some cultures believed cameras steal souls - this one stole dignity.",
      "This image makes me understand genocide - of pixels.",
      "I've seen more beauty in a colonoscopy video.",
      "This photo is what happens when ambition dies and denial takes over.",
      "Your work is a compelling argument for censorship.",
      "This has less class than a crack house.",
      "The quality here makes me nostalgic for the plague.",
      "This photo is visual terrorism.",
      "I've seen more talent in a vegetative state.",
      "This image is what rock bottom looks like from below.",
      "Your photo is proof that some mistakes can't be undone.",
      "This makes me believe in hell because someone needs to pay for this.",
      "The bar was in hell and you brought mining equipment.",
      "This photo is why therapists have therapists.",
      "Your work here is a crime against humanity.",
      "This image has less value than the storage it occupies.",
      "I've seen more promise in a suicide note.",
      "This photo makes strong arguments for the apocalypse.",
      "You've created visual cancer and it's metastasizing.",
      "This image is what happens when hope commits suicide.",
      "Your photo has the redeeming qualities of a war atrocity.",
      "This is visual proof that God has abandoned us.",
      "I've seen more beauty in crime scene photos.",
      "This photo is why some people deserve blindness.",
      "Your work here is a compelling case for nuclear winter.",
      "This image has less value than the electricity used to display it.",
      "You've created something that makes death seem merciful.",
      "This photo is the visual equivalent of terminal illness.",
      "Your aesthetic is 'aftermath of a tragedy.'"
    ]
  }
}

/**
 * Get a random roast based on intensity and image type
 */
export function getRandomRoast(intensity: 'mild' | 'spicy' | 'nuclear', imageType: 'selfie' | 'group' | 'general'): string {
  const roasts = ROAST_LIBRARY[intensity][imageType]
  return roasts[Math.floor(Math.random() * roasts.length)]
}

/**
 * Determine image type from analysis
 */
export function detectImageType(analysis: string): 'selfie' | 'group' | 'general' {
  const lowerAnalysis = analysis.toLowerCase()

  if (lowerAnalysis.includes('selfie') || lowerAnalysis.includes('portrait') || lowerAnalysis.includes('single person')) {
    return 'selfie'
  }

  if (lowerAnalysis.includes('group') || lowerAnalysis.includes('people') || lowerAnalysis.includes('friends') || lowerAnalysis.includes('multiple')) {
    return 'group'
  }

  return 'general'
}